version: '3'

services:
  example-service:
    build: .
    volumes:
      - .:/usr/src/service
      - /usr/src/service/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: yarn start
